/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as ExercicioRouteImport } from './routes/exercicio'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IntroRouteImport } from './routes/intro'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PlanoRouteImport } from './routes/plano'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as TreinoRouteImport } from './routes/treino'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as QuizAlturaRouteImport } from './routes/quiz.altura'
import { Route as QuizConsistenciaRouteImport } from './routes/quiz.consistencia'
import { Route as QuizFrequenciaRouteImport } from './routes/quiz.frequencia'
import { Route as QuizGeneroRouteImport } from './routes/quiz.genero'
import { Route as QuizIdadeRouteImport } from './routes/quiz.idade'
import { Route as QuizLocalRouteImport } from './routes/quiz.local'
import { Route as QuizNivelRouteImport } from './routes/quiz.nivel'
import { Route as QuizNomeRouteImport } from './routes/quiz.nome'
import { Route as QuizObjetivoRouteImport } from './routes/quiz.objetivo'
import { Route as QuizPesoRouteImport } from './routes/quiz.peso'
import { Route as QuizTempoRouteImport } from './routes/quiz.tempo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioRoute = ExercicioRouteImport.update({
  id: '/exercicio',
  path: '/exercicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroRoute = IntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanoRoute = PlanoRouteImport.update({
  id: '/plano',
  path: '/plano',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoRoute = TreinoRouteImport.update({
  id: '/treino',
  path: '/treino',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizAlturaRoute = QuizAlturaRouteImport.update({
  id: '/quiz/altura',
  path: '/quiz/altura',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizConsistenciaRoute = QuizConsistenciaRouteImport.update({
  id: '/quiz/consistencia',
  path: '/quiz/consistencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizFrequenciaRoute = QuizFrequenciaRouteImport.update({
  id: '/quiz/frequencia',
  path: '/quiz/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizGeneroRoute = QuizGeneroRouteImport.update({
  id: '/quiz/genero',
  path: '/quiz/genero',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIdadeRoute = QuizIdadeRouteImport.update({
  id: '/quiz/idade',
  path: '/quiz/idade',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizLocalRoute = QuizLocalRouteImport.update({
  id: '/quiz/local',
  path: '/quiz/local',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNivelRoute = QuizNivelRouteImport.update({
  id: '/quiz/nivel',
  path: '/quiz/nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizNomeRoute = QuizNomeRouteImport.update({
  id: '/quiz/nome',
  path: '/quiz/nome',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizObjetivoRoute = QuizObjetivoRouteImport.update({
  id: '/quiz/objetivo',
  path: '/quiz/objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizPesoRoute = QuizPesoRouteImport.update({
  id: '/quiz/peso',
  path: '/quiz/peso',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizTempoRoute = QuizTempoRouteImport.update({
  id: '/quiz/tempo',
  path: '/quiz/tempo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/exercicio': typeof ExercicioRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/progresso': typeof ProgressoRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/quiz/altura': typeof QuizAlturaRoute
  '/quiz/consistencia': typeof QuizConsistenciaRoute
  '/quiz/frequencia': typeof QuizFrequenciaRoute
  '/quiz/genero': typeof QuizGeneroRoute
  '/quiz/idade': typeof QuizIdadeRoute
  '/quiz/local': typeof QuizLocalRoute
  '/quiz/nivel': typeof QuizNivelRoute
  '/quiz/nome': typeof QuizNomeRoute
  '/quiz/objetivo': typeof QuizObjetivoRoute
  '/quiz/peso': typeof QuizPesoRoute
  '/quiz/tempo': typeof QuizTempoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/exercicio': typeof ExercicioRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/progresso': typeof ProgressoRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/quiz/altura': typeof QuizAlturaRoute
  '/quiz/consistencia': typeof QuizConsistenciaRoute
  '/quiz/frequencia': typeof QuizFrequenciaRoute
  '/quiz/genero': typeof QuizGeneroRoute
  '/quiz/idade': typeof QuizIdadeRoute
  '/quiz/local': typeof QuizLocalRoute
  '/quiz/nivel': typeof QuizNivelRoute
  '/quiz/nome': typeof QuizNomeRoute
  '/quiz/objetivo': typeof QuizObjetivoRoute
  '/quiz/peso': typeof QuizPesoRoute
  '/quiz/tempo': typeof QuizTempoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/exercicio': typeof ExercicioRoute
  '/home': typeof HomeRoute
  '/intro': typeof IntroRoute
  '/onboarding': typeof OnboardingRoute
  '/pagamento': typeof PagamentoRoute
  '/plano': typeof PlanoRoute
  '/premium': typeof PremiumRoute
  '/progresso': typeof ProgressoRoute
  '/treino': typeof TreinoRoute
  '/treinos': typeof TreinosRoute
  '/quiz/altura': typeof QuizAlturaRoute
  '/quiz/consistencia': typeof QuizConsistenciaRoute
  '/quiz/frequencia': typeof QuizFrequenciaRoute
  '/quiz/genero': typeof QuizGeneroRoute
  '/quiz/idade': typeof QuizIdadeRoute
  '/quiz/local': typeof QuizLocalRoute
  '/quiz/nivel': typeof QuizNivelRoute
  '/quiz/nome': typeof QuizNomeRoute
  '/quiz/objetivo': typeof QuizObjetivoRoute
  '/quiz/peso': typeof QuizPesoRoute
  '/quiz/tempo': typeof QuizTempoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/exercicio'
    | '/home'
    | '/intro'
    | '/onboarding'
    | '/pagamento'
    | '/plano'
    | '/premium'
    | '/progresso'
    | '/treino'
    | '/treinos'
    | '/quiz/altura'
    | '/quiz/consistencia'
    | '/quiz/frequencia'
    | '/quiz/genero'
    | '/quiz/idade'
    | '/quiz/local'
    | '/quiz/nivel'
    | '/quiz/nome'
    | '/quiz/objetivo'
    | '/quiz/peso'
    | '/quiz/tempo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/exercicio'
    | '/home'
    | '/intro'
    | '/onboarding'
    | '/pagamento'
    | '/plano'
    | '/premium'
    | '/progresso'
    | '/treino'
    | '/treinos'
    | '/quiz/altura'
    | '/quiz/consistencia'
    | '/quiz/frequencia'
    | '/quiz/genero'
    | '/quiz/idade'
    | '/quiz/local'
    | '/quiz/nivel'
    | '/quiz/nome'
    | '/quiz/objetivo'
    | '/quiz/peso'
    | '/quiz/tempo'
  id:
    | '__root__'
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/exercicio'
    | '/home'
    | '/intro'
    | '/onboarding'
    | '/pagamento'
    | '/plano'
    | '/premium'
    | '/progresso'
    | '/treino'
    | '/treinos'
    | '/quiz/altura'
    | '/quiz/consistencia'
    | '/quiz/frequencia'
    | '/quiz/genero'
    | '/quiz/idade'
    | '/quiz/local'
    | '/quiz/nivel'
    | '/quiz/nome'
    | '/quiz/objetivo'
    | '/quiz/peso'
    | '/quiz/tempo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  ExercicioRoute: typeof ExercicioRoute
  HomeRoute: typeof HomeRoute
  IntroRoute: typeof IntroRoute
  OnboardingRoute: typeof OnboardingRoute
  PagamentoRoute: typeof PagamentoRoute
  PlanoRoute: typeof PlanoRoute
  PremiumRoute: typeof PremiumRoute
  ProgressoRoute: typeof ProgressoRoute
  TreinoRoute: typeof TreinoRoute
  TreinosRoute: typeof TreinosRoute
  QuizAlturaRoute: typeof QuizAlturaRoute
  QuizConsistenciaRoute: typeof QuizConsistenciaRoute
  QuizFrequenciaRoute: typeof QuizFrequenciaRoute
  QuizGeneroRoute: typeof QuizGeneroRoute
  QuizIdadeRoute: typeof QuizIdadeRoute
  QuizLocalRoute: typeof QuizLocalRoute
  QuizNivelRoute: typeof QuizNivelRoute
  QuizNomeRoute: typeof QuizNomeRoute
  QuizObjetivoRoute: typeof QuizObjetivoRoute
  QuizPesoRoute: typeof QuizPesoRoute
  QuizTempoRoute: typeof QuizTempoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio': {
      id: '/exercicio'
      path: '/exercicio'
      fullPath: '/exercicio'
      preLoaderRoute: typeof ExercicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intro': {
      id: '/intro'
      path: '/intro'
      fullPath: '/intro'
      preLoaderRoute: typeof IntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plano': {
      id: '/plano'
      path: '/plano'
      fullPath: '/plano'
      preLoaderRoute: typeof PlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino': {
      id: '/treino'
      path: '/treino'
      fullPath: '/treino'
      preLoaderRoute: typeof TreinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/altura': {
      id: '/quiz/altura'
      path: '/quiz/altura'
      fullPath: '/quiz/altura'
      preLoaderRoute: typeof QuizAlturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/consistencia': {
      id: '/quiz/consistencia'
      path: '/quiz/consistencia'
      fullPath: '/quiz/consistencia'
      preLoaderRoute: typeof QuizConsistenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/frequencia': {
      id: '/quiz/frequencia'
      path: '/quiz/frequencia'
      fullPath: '/quiz/frequencia'
      preLoaderRoute: typeof QuizFrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/genero': {
      id: '/quiz/genero'
      path: '/quiz/genero'
      fullPath: '/quiz/genero'
      preLoaderRoute: typeof QuizGeneroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/idade': {
      id: '/quiz/idade'
      path: '/quiz/idade'
      fullPath: '/quiz/idade'
      preLoaderRoute: typeof QuizIdadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/local': {
      id: '/quiz/local'
      path: '/quiz/local'
      fullPath: '/quiz/local'
      preLoaderRoute: typeof QuizLocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/nivel': {
      id: '/quiz/nivel'
      path: '/quiz/nivel'
      fullPath: '/quiz/nivel'
      preLoaderRoute: typeof QuizNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/nome': {
      id: '/quiz/nome'
      path: '/quiz/nome'
      fullPath: '/quiz/nome'
      preLoaderRoute: typeof QuizNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/objetivo': {
      id: '/quiz/objetivo'
      path: '/quiz/objetivo'
      fullPath: '/quiz/objetivo'
      preLoaderRoute: typeof QuizObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/peso': {
      id: '/quiz/peso'
      path: '/quiz/peso'
      fullPath: '/quiz/peso'
      preLoaderRoute: typeof QuizPesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/tempo': {
      id: '/quiz/tempo'
      path: '/quiz/tempo'
      fullPath: '/quiz/tempo'
      preLoaderRoute: typeof QuizTempoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  ExercicioRoute: ExercicioRoute,
  HomeRoute: HomeRoute,
  IntroRoute: IntroRoute,
  OnboardingRoute: OnboardingRoute,
  PagamentoRoute: PagamentoRoute,
  PlanoRoute: PlanoRoute,
  PremiumRoute: PremiumRoute,
  ProgressoRoute: ProgressoRoute,
  TreinoRoute: TreinoRoute,
  TreinosRoute: TreinosRoute,
  QuizAlturaRoute: QuizAlturaRoute,
  QuizConsistenciaRoute: QuizConsistenciaRoute,
  QuizFrequenciaRoute: QuizFrequenciaRoute,
  QuizGeneroRoute: QuizGeneroRoute,
  QuizIdadeRoute: QuizIdadeRoute,
  QuizLocalRoute: QuizLocalRoute,
  QuizNivelRoute: QuizNivelRoute,
  QuizNomeRoute: QuizNomeRoute,
  QuizObjetivoRoute: QuizObjetivoRoute,
  QuizPesoRoute: QuizPesoRoute,
  QuizTempoRoute: QuizTempoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
